# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Biostats
tagline:             learning to analyze data
#url:                 http://getpoole.com
paginate:            1
url:                 http://mlammens.github.io/
baseurl:             /Biostats
#baseurl:             http://mlammens.github.io/Biostats

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Matt Lammens
  url:               
  email:             

pages_list:       
  About: '/Biostats/about'
  Syllabus: '/Biostats/syllabus'
  Resources: '/Biostats/resources'
  Archive: '/Biostats/archive'
  #About: '/about'
  #Archive: '/archive'
  #Feed: '/atom.xml'
  
# Custom vars
version:             2.0.0
github:
  repo:              
